export const SetPayments = 'SetPayments'
export const DeletePayment = 'DeletePayment'
export const SetEditPayment = 'SetEditPayment'
export const SetPaymentAlertStatus = 'SetPaymentAlertStatus'
export const SetPaymentAlertText = 'SetPaymentAlertText'
